name: brew_buds
description: "The Brew Buds Coffee SNS Project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: 3.4.0
  provider: ^6.1.2
  go_router: ^14.2.7
  dio: ^5.7.0

  flutter_secure_storage:
  kakao_flutter_sdk:
  flutter_naver_login: ^1.7.0
  sign_in_with_apple: ^6.1.3
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  animations: ^2.0.11
  retrofit: ^4.4.1
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  debounce_throttle: ^2.0.0
  modal_bottom_sheet: ^3.0.0
  sliver_tools: ^0.2.12
  velocity_x: ^4.2.1
  get: ^4.6.6
  flutter_native_splash:
  syncfusion_flutter_sliders: 25.2.4
  syncfusion_flutter_core: ^25.2.7
  image_picker: ^1.1.2
  photo_manager: ^3.6.2
  photo_manager_image_provider: ^2.2.0
  camera: ^0.11.0+2
  flutter_slidable: ^3.1.2

flutter_native_splash:
  color: "#42a5f5"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  retrofit_generator: '>=8.0.0 <10.0.0'

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/coffee.jpeg
    - assets/images/login/
    - assets/icons/


  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900

