name: brew_buds
description: "The Brew Buds Coffee SNS Project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.13.0
  provider: ^6.1.2
  go_router: ^14.8.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.4
  kakao_flutter_sdk: ^1.9.7+3
  flutter_naver_login: ^2.0.0
  sign_in_with_apple: ^6.1.3
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  animations: ^2.0.11
  retrofit: ^4.4.1
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  debounce_throttle: ^2.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_native_splash:
  syncfusion_flutter_sliders: 25.2.4
  syncfusion_flutter_core: ^25.2.7
  photo_manager: ^3.6.2
  photo_manager_image_provider: ^2.2.0
  flutter_slidable: ^3.1.2
  permission_handler: ^11.3.1
  flutter_staggered_grid_view: ^0.7.0
  extended_image: ^9.1.0
  table_calendar: ^3.0.9
  fl_chart: ^0.70.2
  camerawesome: ^2.1.0
  path_provider: ^2.1.4
  defer_pointer: ^0.0.2
  image_editor: ^1.6.0
  flutter_image_compress: ^2.3.0
  flutter_localization: ^0.2.1
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.2.3
  super_tooltip: ^2.0.9
  package_info_plus: ^8.0.2
  firebase_messaging: ^15.1.0
  webview_flutter: ^4.8.0
  showcaseview: ^4.0.1
  notification_center: ^1.0.2
  geolocator: ^12.0.0
  flutter_screenutil: ^5.9.3

flutter_native_splash:
  color: "#FFFFFF"
  fullscreen: true
  ios_content_mode: center
  image: assets/images/brewbuds_primary_logo_white.png

flutter_launcher_icons:
  ios: "AppIcon"
  image_path_ios: "assets/images/brewbuds_primary_logo_red.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  retrofit_generator: '>=8.0.0 <10.0.0'

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/login/
    - assets/icons/


  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900

