# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "Deploy to Firebase App Distribution"
    lane :firebase do
        build_app(
          workspace: "Runner.xcworkspace",
          scheme: "Runner",
          export_method: "development"
        ) # iOS 빌드

    firebase_app_distribution(
      app: ENV["IOS_FIREBASE_APP_DISTRIBUTION_APP"], # Firebase에서 확인한 앱 ID
      firebase_cli_token: ENV["FIREBASE_TOKEN"], # Firebase CLI에서 받은 토큰
      groups: "brew_buds_testers", # 배포할 테스터 그룹
      release_notes: "New build for testing" # 릴리스 노트
    )
  end
end