enum Country {
  guatemala,
  nicaragua,
  dominican,
  mexico,
  bolivia,
  brazil,
  ecuador,
  elSalvador,
  honduras,
  jamaica,
  costaRica,
  cuba,
  colombia,
  panama,
  peru,
  rwanda,
  malawi,
  ethiopia,
  uganda,
  cameroon,
  kenya,
  congo,
  tanzania,
  korea,
  laos,
  myanmar,
  vietnam,
  yemen,
  india,
  indonesia,
  papuaNewGuinea,
  philippines,
  hawaii;

  @override
  String toString() => switch (this) {
        Country.guatemala => '과테말라',
        Country.nicaragua => '니카라과',
        Country.mexico => '멕시코',
        Country.bolivia => '볼리비아',
        Country.brazil => '브라질',
        Country.elSalvador => '엘살바도르',
        Country.honduras => '온두라스',
        Country.costaRica => '코스타리카',
        Country.colombia => '콜롬비아',
        Country.panama => '파나마',
        Country.peru => '페루',
        Country.rwanda => '르완다',
        Country.ethiopia => '에티오피아',
        Country.kenya => '케냐',
        Country.india => '인도',
        Country.indonesia => '인도네시아',
        Country.cameroon => '카메룬',
        Country.korea => '대한민국',
        Country.vietnam => '베트남',
        Country.dominican => '도미니카 공화국',
        Country.ecuador => '에콰도',
        Country.jamaica => '자메이카',
        Country.cuba => '쿠바',
        Country.malawi => '말라위',
        Country.uganda => '우간다',
        Country.congo => '콩고',
        Country.tanzania => '탄자니',
        Country.laos => '라오스',
        Country.myanmar => '미얀마',
        Country.yemen => '예멘',
        Country.papuaNewGuinea => '파푸아뉴기니',
        Country.philippines => '필리핀',
        Country.hawaii => '하와이',
      };
}

enum Continent {
  latinAmerica,
  africa,
  etc;

  List<Country> countries() => switch (this) {
        Continent.latinAmerica => [
            Country.guatemala,
            Country.nicaragua,
            Country.dominican,
            Country.mexico,
            Country.bolivia,
            Country.brazil,
            Country.ecuador,
            Country.elSalvador,
            Country.honduras,
            Country.jamaica,
            Country.costaRica,
            Country.cuba,
            Country.colombia,
            Country.panama,
            Country.peru,
          ],
        Continent.africa => [
            Country.rwanda,
            Country.malawi,
            Country.ethiopia,
            Country.uganda,
            Country.cameroon,
            Country.kenya,
            Country.congo,
            Country.tanzania,
          ],
        Continent.etc => [
            Country.korea,
            Country.laos,
            Country.myanmar,
            Country.vietnam,
            Country.yemen,
            Country.india,
            Country.indonesia,
            Country.papuaNewGuinea,
            Country.philippines,
            Country.hawaii
          ],
      };

  @override
  String toString() => switch (this) {
        Continent.latinAmerica => '중남미',
        Continent.africa => '아프리카',
        Continent.etc => '기타',
      };
}
